### ISSUE TITLE
`allbinom(1,1)` causes error

### ISSUE THREAD

**Issue by jassler** [RobinHankin/partitions#36]
Calling `allbinom(1,1)` causes the following error

```r
Warning: Error in [: incorrect number of dimensions
```

Trying to widdle it down, I think the this call causes the problem.

```r
multinomial(c(k, n - k))[seq_len(k), , drop = FALSE]
# Error in multinomial(c(k, n - k))[seq_len(k), , drop = FALSE] : 
#   incorrect number of dimensions
```

This smells like some hidden R shenanigans. Currently, I've just hard-coded the case if both `n == k == 1` and have it return `matrix(1)`.

**Comment by RobinHankin** [comment]
thanks for this, I can confirm the bug.  Currently investigating, will get back to you.
